### ISSUE TITLE
RFID Enrollment 

### ISSUE THREAD

**Issue by EngineControls** [niclasku/rpi-timeclock-terminal#1]
Hi there i am using your project and your fork of the timeclock backend. 

How do i set a RFID tag to a user?

Each time a present a RFID tag it says user does not exist: 10642181129116 
Please can you explain the process to enroll users and set their RFID Tag.

**Comment by niclasku** [comment]
Hi, 

please log in as an admin in the timeclock web interface and click on/go to the "Employees" page. Then there should be a "Terminal" button for each employee. After clicking it, you'll see a form where you can set the RFID tag serial number and upload a picture. 

If this doesn't work, please provide a little more information like screenshots. If it works, please let me know so I can close the issue. 

Thanks!

**Comment by EngineControls** [comment]
Hi there here is a screenshot of the screen, i do not see any terminal button available. 
![image](https://user-images.githubusercontent.com/66062193/140722588-52d5a2bb-81c5-4cc8-9cd0-1e1a9fbf477c.png)

**Comment by niclasku** [comment]
Are you sure you're using [my fork](https://github.com/niclasku/timeclock/) of the timeclock project? I don't see a link to the "Vacation" page in the menu but there should be one: 

https://github.com/niclasku/timeclock/blob/278228ff8ff808f2678d3a3013dd67a822387e99/src/views/layouts/main.php#L77-L82

**Comment by EngineControls** [comment]
So from the raspberry pi i did a git clone https://github.com/niclasku/timeclock.git

**Comment by niclasku** [comment]
That is the proper command, but according to the screenshot you are **not** using my fork. I guess you ran the composer command from my repo (`composer create-project --prefer-dist bizley/timeclock timeclock`) which (wrongly) pointed to the original repo, right? I just updated the install instructions (see [README](https://github.com/niclasku/timeclock/blob/master/README.md)). Please try to install and configure it again using the updated instructions.

**Comment by EngineControls** [comment]
That is correct, i did run the composer create-project --prefer-dist bizley/timeclock timeclock command. 

I will try the updated install instructions now and give you feedback. 
Thank you so much for going out of your way to assist me, i really do appreciate it.

**Comment by EngineControls** [comment]
I have followed the new instructions and i have managed to get it all to work. Thank you once again for assisting me :)

I have one last question the we can close this:

I am using the official 7inch touch screen and case https://www.raspberrypi.com/products/raspberry-pi-touch-display/ for this project but i cannot get the touch screen to work?

The touchscreen and everything works perfectly on the raspberry pi, desktop and all other applications. 
But when the terminal autoload's or runs then the touchscreen does not work.

**Comment by niclasku** [comment]
Nice :) I do not have an official rpi touchscreen, but as the timeclock terminal uses kivy this might help: https://kivy.org/doc/stable/installation/installation-rpi.html#using-official-rpi-touch-display

**Comment by EngineControls** [comment]
Hi there everything is working thank you, you can close this :) 

Thank you for all your help man. 
Below i posted the changed to make the display work. 

If you are using the official Raspberry Pi touch display, you need to configure Kivy to use it as an input source. To do this, edit the file ~/.kivy/config.ini and go to the [input] section. Add this:

mouse = mouse
mtdev_%(name)s = probesysfs,provider=mtdev
hid_%(name)s = probesysfs,provider=hidinput
